name: Build Rescue ISO

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm archiso make

      - name: Prepare Custom Profile
        run: |
          cp -r /usr/share/archiso/configs/releng/ /tmp/custom-profile
          cp -r ./custom-profile/* /tmp/custom-profile/

      - name: Build the ISO
        run: |
          # Run mkarchiso against the newly combined profile
          mkarchiso -v -w /tmp/work -o /tmp/out /tmp/custom-profile

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rescue-usb-iso
          path: /tmp/out/*.iso
          retention-days: 5
